#!/bin/bash

if tput setaf 1 &> /dev/null; then
    tput sgr0; # reset colors
    bold="\[$(tput bold)\]";
    italic="\[$(tput sitm)\]";
    reset="\[$(tput sgr0)\]";
    black="\[$(tput setaf 235)\]"
    red="\[$(tput setaf 1)\]"
    green="\[$(tput setaf 106)\]"
    yellow="\[$(tput setaf 214)\]"
    blue="\[$(tput setaf 66)\]"
    purple="\[$(tput setaf 175)\]"
    cyan="\[$(tput setaf 37)\]"
    gray="\[$(tput setaf 246)\]"
    white="\[$(tput setaf 223)\]"
    orange="\[$(tput setaf 166)\]"
    light_black="\[$(tput setaf 236)\]"
else
    bold="\[\e[1m\]";
    italic="\[\e[3m\]";
    reset="\[\e[0m\]";
    black="\[\e[1;30m\]";
    blue="\[\e[1;34m\]";
    cyan="\[\e[1;36m\]";
    green="\[\e[1;32m\]";
    orange="\[\e[1;33m\]";
    purple="\[\e[1;35m\]";
    red="\[\e[1;31m\]";
    violet="\[\e[1;35m\]";
    white="\[\e[1;37m\]";
    yellow="\[\e[1;33m\]";
fi;

find_git_branch() {
  # Based on: http://stackoverflow.com/a/13003854/170413
  local branch
  if branch=$(git rev-parse --abbrev-ref HEAD 2> /dev/null); then
    if [[ "$branch" == "HEAD" ]]; then
      branch='detached*'
    fi
    echo "${yellow}(${branch})${reset} "
  else
    echo ""
  fi
}

find_git_dirty() {
  local status=$(git status --porcelain 2> /dev/null)
  if [[ "$status" != "" ]]; then
    echo '*'
  else
    echo ''
  fi
}

# Determine active Python virtualenv details.
find_virtualenv() {
    if test -z "$VIRTUAL_ENV" ; then
        echo ""
    else
        echo "$cyan[`basename \"$VIRTUAL_ENV\"`] "
    fi
}

# Highlight the user name when logged in as root.
if [[ "$USER" == "root" ]]; then
    user="${bold}${italic}$red\u${reset}";
else
    user="${gray}\u${reset}";
fi;

host="${italic}${orange}\H${reset}";
dir="${cyan}\w${reset}"
separator="${gray} \[•\] ${reset}"

function prompt_command {
    ret_code=$?
    # Are we running in a shell invoked from Vim?
    if [[ "$VIM" ]]; then
        vim="${red}(Vim)${reset} "
    else
        vim=""
    fi

    # Did last command return non-zero value?
    if [ "${ret_code}" != 0 ]; then
        ret_str="${red}${ret_code}>${reset} "
    else
        ret_str="${green}\$${reset} "
    fi

    PS1="${user}${separator}${host}${separator}${dir}\n${vim}$(find_virtualenv)$(find_git_branch)${ret_str}"
}

PROMPT_COMMAND=prompt_command
export PS2="${blue}.... ${reset}"
